### YamlMime:Yaml
ms.openlocfilehash: b18d6e81a39093faa7de65b5fd1068a7e6a1c68bca678119782acdf49c77d6ed
ms.sourcegitcommit: 27285bbc4a032991d55a7cf0499a89f2d0a89363
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 08/11/2021
ms.locfileid: "58180203"
default:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<:
    adapter: sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
  database: db/development.sqlite3
test:
  <<:
    adapter: sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
  database: db/test.sqlite3
production:
  <<:
    adapter: sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
  database: db/production.sqlite3
