### YamlMime:Yaml
ms.openlocfilehash: a52c89c85053e039f8f92dc37c6e090d41b75234785c7c99d73dc5b4eae82b3c
ms.sourcegitcommit: 27285bbc4a032991d55a7cf0499a89f2d0a89363
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 08/11/2021
ms.locfileid: "58180133"
Layout/ArgumentAlignment:
  Exclude:
  - bin/webpack
  - bin/webpack-dev-server
Layout/DotPosition:
  Exclude:
  - bin/yarn
Layout/EmptyLineAfterGuardClause:
  Exclude:
  - bin/bundle
Layout/EmptyLinesAroundBlockBody:
  Exclude:
  - db/schema.rb
Layout/MultilineMethodCallIndentation:
  Exclude:
  - bin/yarn
Layout/MultilineOperationIndentation:
  Exclude:
  - bin/bundle
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
  - config/environments/production.rb
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 212
Metrics/ParameterLists:
  Max: 7
Metrics/PerceivedComplexity:
  Max: 9
Style/ClassAndModuleChildren:
  Exclude:
  - test/channels/application_cable/connection_test.rb
  - test/test_helper.rb
Style/Documentation:
  Exclude:
  - spec/**/*
  - test/**/*
  - app/controllers/auth_controller.rb
  - app/controllers/home_controller.rb
  - app/helpers/application_helper.rb
  - app/helpers/auth_helper.rb
  - app/helpers/calendar_helper.rb
  - app/helpers/home_helper.rb
  - app/models/application_record.rb
  - config/application.rb
  - db/migrate/20210427151603_add_sessions_table.rb
Style/ExpandPathArguments:
  Exclude:
  - bin/bundle
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Exclude:
  - config/environments/production.rb
Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Exclude:
  - Gemfile
  - app/mailers/application_mailer.rb
  - config/initializers/wrap_parameters.rb
Style/IfUnlessModifier:
  Exclude:
  - bin/bundle
Style/InverseMethods:
  Exclude:
  - bin/yarn
Style/NumericLiterals:
  Exclude:
  - db/schema.rb
Style/PerlBackrefs:
  Exclude:
  - bin/bundle
Style/RedundantFetchBlock:
  Exclude:
  - config/puma.rb
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Style/StderrPuts:
  Exclude:
  - bin/yarn
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Layout/LineLength:
  Max: 198
